version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: miusuario
      POSTGRES_PASSWORD: mipassword
      POSTGRES_DB: mibasededatos
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d
    networks:
      - red_app

  backend:
    build: ./backend  # Dockerfile aquí debe tener el manager + WAR
    container_name: backend
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/data/logs
      - ./backend/backup:/usr/local/tomcat/data/database/backups
    networks:
      - red_app
    environment:
      SPRING_PROFILES_ACTIVE: prod

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - red_app

networks:
  red_app:
    driver: bridge
